package com.itsectest.shared.audit.api;

public enum AuditAction {

    REGISTER,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGIN_BLOCKED,
    ACCOUNT_LOCKED,
    OTP_ISSUED,
    OTP_VERIFIED,
    OTP_FAILED,
    OTP_RESENT,
    TOKEN_REFRESHED,
    LOGOUT,

    USER_CREATED,
    USER_VIEWED,
    USER_LIST_VIEWED,
    USER_UPDATED,
    USER_DELETED,

    ARTICLE_CREATED,
    ARTICLE_VIEWED,
    ARTICLE_LIST_VIEWED,
    ARTICLE_UPDATED,
    ARTICLE_DELETED,

    AUDIT_LOG_VIEWED,

    RATE_LIMIT_EXCEEDED,
    ACCESS_DENIED
}
